---
name: "AniDB"
guid: "a2b2a7ed-aa28-4521-a64a-63d86901f246"
version: "1.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
owner: "jellyfin"
overview: "AniDB metadata provider"
description: >
  AniDB metadata provider
category: "Metadata"
artifacts:
- "Jellyfin.Plugin.AniDB.dll"
changelog: >
  - Split out from the Anime plugin
